font_family      GeistMonoNF-Semibold
bold_font        GeistMonoNF-Bold
italic_font      GeistMonoNF-Medium
bold_italic_font GeistMonoNF-Bold

font_size 10

adjust_line_height 130%
adjust_column_width 105%

include gruvbox-dark-hard.conf
include font-nerd-symbols.conf
