color0 #111416
color1 #ffb4ab
color2 #85cfff
color3 #b6c9d8
color4 #cdc0e9
color5 #85cfff
color6 #b6c9d8
color7 #e2e2e5
color8 #8b9198
color9 #ffb4ab
color10 #85cfff
color11 #b6c9d8
color12 #cdc0e9
color13 #85cfff
color14 #b6c9d8
color15 #e2e2e5

cursor                #e2e2e5
cursor_text_color     #111416
background            #111416
foreground            #e2e2e5
selection_foreground  #c1c7ce
selection_background  #41484d
active_border_color   #85cfff
inactive_border_color #41484d
url_color             #85cfff

active_tab_foreground   #00344c
active_tab_background   #85cfff
inactive_tab_foreground #c1c7ce
inactive_tab_background #41484d
cursor_trail_color      #c1c7ce
