# For Laptop display
# font_family      GeistMonoNF-Semibold
# bold_font        GeistMonoNF-Bold
# italic_font      GeistMonoNF-Medium
# bold_italic_font GeistMonoNF-Bold

# For larger display
# font_family      Geist Mono Regular
# bold_font        Geist Mono Semibold
# italic_font      Geist Mono Regular
# bold_italic_font Geist Mono Semibold

# For Laptop display
# font_size	11.7

# For larger display
# font_size	9.4

# For larger display
# font_size	10.8

# For larger display
font_size	10

# For Laptop display
adjust_line_height    130%
# adjust_line_height    120%
# adjust_column_width   94%
# adjust_column_width   98%
adjust_column_width   105%
# adjust_column_width   108%

# For larger display
# adjust_line_height    115%
# adjust_column_width   95%

remember_window_size  yes
initial_window_width  1440
initial_window_height 1080
window_padding_width 16 12 16 12
hide_window_decorations yes
tab_bar_margin_height 10.0 0.0
tab_bar_style custom
tab_fade 0 0 0 0
background_opacity 0.89
dynamic_background_opacity yes

include gruvbox-dark-hard.conf
include font-nerd-symbols.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS